CREATE TABLE IF NOT EXISTS sales.stg_sales_raw (
    ordernumber        INTEGER,
    quantityordered    INTEGER,
    priceeach          NUMERIC(10,2),
    orderlinenumber    INTEGER,
    sales              NUMERIC(12,2),
    orderdate          DATE,
    status             TEXT,
    qtr_id             INTEGER,
    month_id           INTEGER,
    year_id            INTEGER,
    productline        TEXT,
    msrp               INTEGER,
    productcode        TEXT,
    customername       TEXT,
    phone              TEXT,
    addressline1       TEXT,
    addressline2       TEXT,
    city               TEXT,
    state              TEXT,
    postalcode         TEXT,
    country            TEXT,
    territory          TEXT,
    contactlastname    TEXT,
    contactfirstname   TEXT,
    dealsize           TEXT
);